### ISSUE TITLE
Feature idea: Multiple line comments

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark-usage#10]
Just a thought that randomly came to me... it'd be nice to have multi-line comments in the example files.

So instead of writing this:

```js
console.log('sh', 'yarn global add foo');
console.log('sh', 'foo bar --baz');
```

You could write this:

```js
console.log('sh', `
yarn global add foo
foo bar --baz
`);
```

Not sure if that's best approach, something probably better could be thought of.

cc @wooorm

**Comment by wooorm** [comment]
Doesn’t this already work? Looks like it:

https://github.com/wooorm/remark-usage/blob/a92255ec431c74169c9a3ca80cdf97f77b5fbfb7/index.js#L36

**Comment by wooorm** [comment]
@niftylettuce Ping!
