### ISSUE TITLE
Multi-line console logging

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark-usage#11]
```js
console.log(
  'sh',
  require('child_process')
    .execSync('tree new-package -I "node_modules|media|coverage"')
    .toString()
);
```

Outputs this unfortunately instead of the second arg invoked:

```md

```javascript

console.log(
  'sh',
  require('child_process')
    .execSync('tree new-package -I "node_modules|media|coverage"')
    .toString()
);
```

```

**Comment by wooorm** [comment]
The readme notes the following:

> - **Don’t do weird things. This is mostly regexes**

If you’d like to have this, PRs are welcome!

**Comment by wooorm** [comment]
Closing the issue to remove it from my todo list, but still, PRs are super welcome!
