### ISSUE TITLE
possible build problem with the latest release?

### ISSUE THREAD

**Issue by travi** [wooorm/remark-usage#15]
### Subject of the issue

when trying to load v7.0.0 into my .remarkrc.js, the same way i did with the previous version, i'm now met with an error:

```
Error: Cannot parse file `.remarkrc.js`
Cannot parse script `node_modules/remark-usage/index.js`
Error: Cannot find module './lib'
```

upon inspection of the `node_modules/remark-usage/` directory, there is, in fact, no `lib/` present

### Your environment

*   **OS**: macOS 10.14.5
*   **Packages**: https://github.com/travi/javascript-scaffolder/tree/greenkeeper/remark-usage-7.0.0
*   **Env**: 
```
$ node -v
v10.16.0
$ npm -v
6.9.0
```

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

1. clone and checkout branch: https://github.com/travi/javascript-scaffolder/tree/greenkeeper/remark-usage-7.0.0
1. `npm run generate:md`

### Expected behaviour

What should happen?

remark should rebuild me `README.md` and include usage details from `example.js`

### Actual behaviour

What happens instead?

error described above is shown

**Comment by wooorm** [comment]
Whoops, thanks for reporting, fixed!

**Comment by travi** [comment]
thanks for the quick resolution! also the new [transpilation support](https://github.com/remarkjs/remark-usage/issues/13) seems to be working great!
