### ISSUE TITLE
Bug with mdast-util-heading-range@v2.1.0

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark-usage#7]
```
README.md
            1:1  error    TypeError: Cannot read property 'example' of undefined
    at /Users/niftylettuce/Public/lass/node_modules/remark-usage/index.js:261:35
    at String.replace (<anonymous>)
    at script (/Users/niftylettuce/Public/lass/node_modules/remark-usage/index.js:260:19)
    at postprocess (/Users/niftylettuce/Public/lass/node_modules/remark-usage/index.js:81:28)
    at run (/Users/niftylettuce/Public/lass/node_modules/remark-usage/index.js:240:7)
    at search (/Users/niftylettuce/Public/lass/node_modules/remark-usage/node_modules/mdast-util-heading-range/index.js:82:13)
    at headingRange (/Users/niftylettuce/Public/lass/node_modules/remark-usage/node_modules/mdast-util-heading-range/index.js:36:3)
    at /Users/niftylettuce/Public/lass/node_modules/remark-usage/index.js:175:5
    at wrapped (/Users/niftylettuce/Public/lass/node_modules/trough/index.js:93:19)
    at next (/Users/niftylettuce/Public/lass/node_modules/trough/index.js:56:24)
```

**Comment by wooorm** [comment]
You need to provide much more info. All tests are working as expected.

**Comment by niftylettuce** [comment]
See #8

**Comment by wooorm** [comment]
😨

Could you add a test case that used to fail, but now doesn't anymore, so we can prevent this in the future?

**Comment by niftylettuce** [comment]
@wooorm not sure what I did to cause it yet tbh 😆

**Comment by wooorm** [comment]
Seems to be based on the example you have it!

**Comment by niftylettuce** [comment]
@wooorm it was because of a missing closing HTML tag in my markdown - I'm not sure how to write a test case for this.  e.g. `// <sub>Some foo bar baz` (note the missing `</sub>`)

**Comment by niftylettuce** [comment]
@wooorm can you figure out how to write a test for this?  here was my example file (note the missing closing tag for `</sub`> at the very top

```js
// <sub>This section is automatically rendered from [example.js](example.js).

// ### Install

// [npm][]:

console.log('sh', 'npm install -g sao');
console.log('sh', 'sao lass new-project');

// [yarn][]:

console.log('sh', 'yarn global add sao');
console.log('sh', 'sao lass new-project');

// ### Structure

console.log(
  'sh',
  require('child_process').execSync('tree new-project').toString()
);
```

**Comment by wooorm** [comment]
Take a look at the [fixtures](https://github.com/wooorm/remark-usage/tree/master/test/fixtures)!

1. You don’t need to touch `test/index.js`, just create a new fixture directory with the correct files (look at ones already there).
2. I’d also suggest using a name like `issue-7` and linking to this issue in `readme.md`!
3. Also try to use the shortest `example.js` possible: try to keep only the failing lines!

**Comment by wooorm** [comment]
Anyway, let’s talk over on GH-8 on how to implement the fix!
